site_name: Alan Wade
site_description: A collection of my projects and blog posts
site_url: https://a-wade.com

nav:
  - Home:
    - About: index.md 
  - Portfolio:
    - Projects: portfolio/index.md
  - FAQ:
    - Frequently Asked Questions: faq/index.md

theme:
  name: material
  palette:
    - scheme: default
      primary: '#2D4654'
      accent: '#489FB5' 
  features:
    - search.suggest
    - toc.integrate
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  language: en
  font:
    text: Montserrat
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alan-wade
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alan-j-wade/
  analytics:
    # provider: google
    # property: G-W9Y130NXVZ

extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#2D4654"

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.keys

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js